### ISSUE TITLE
Policy Store API (Create Policy) throws NullPointerException

### ISSUE THREAD

**Issue by ds-mwesener** [eclipse-tractusx/item-relationship-service#436]
## Description

PolicyStore API is accepting either "AND" constraints as list or "OR" constraints as list. Or both.
## Current behaviour
If only "AND" or either only "OR" will be provided it leads to a nullpointer exception within the ConstraintCheckerService
## Expected behavior

Refactor method to be nullsafe.

## Steps to reproduce the Bug

Create a policy with the api and only include "AND" constraint.
![image](https://github.com/eclipse-tractusx/item-relationship-service/assets/124587888/4fdac444-ac73-4a74-a5d7-a0665347b3ed)

## Stacktrace:

	at org.eclipse.tractusx.irs.edc.client.policy.PolicyCheckerService.lambda$isValid$1(PolicyCheckerService.java:52)	at java.base/java.util.stream.MatchOps$1MatchSink.accept(Unknown Source)	at java.base/java.util.AbstractList$RandomAccessSpliterator.tryAdvance(Unknown Source)	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)	at java.base/java.util.stream.ReferencePipeline.anyMatch(Unknown Source)	at org.eclipse.tractusx.irs.edc.client.policy.PolicyCheckerService.isValid(PolicyCheckerService.java:52)	at org.eclipse.tractusx.irs.edc.client.policy.PolicyCheckerService.lambda$isValid$0(PolicyCheckerService.java:47)	at java.base/java.util.stream.MatchOps$1MatchSink.accept(Unknown Source)	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)	at java.base/java.util.stream.ReferencePipeline.allMatch(Unknown Source)	at org.eclipse.tractusx.irs.edc.client.policy.PolicyCheckerService.isValid(PolicyCheckerService.java:47)	at org.eclipse.tractusx.irs.edc.client.ContractNegotiationService.startNewNegotiation(ContractNegotiationService.java:125)	at org.eclipse.tractusx.irs.edc.client.ContractNegotiationService.negotiate(ContractNegotiationService.java:85)	at org.eclipse.tractusx.irs.edc.client.EdcSubmodelClientImpl.getEndpointReferenceForAsset(EdcSubmodelClientImpl.java:226)	at org.eclipse.tractusx.irs.edc.client.EdcSubmodelClientImpl.lambda$getEndpointReferenceForAsset$4(EdcSubmodelClientImpl.java:209)	at io.github.resilience4j.retry.Retry.lambda$decorateCallable$5(Retry.java:237)	at org.eclipse.tractusx.irs.edc.client.EdcSubmodelClientImpl.execute(EdcSubmodelClientImpl.java:282)	... 7 more

**Comment by ds-jhartmann** [comment]
Thanks for raising this Bug. It was fixed with https://github.com/eclipse-tractusx/item-relationship-service/pull/458 and is already available in irs-edc-client 1.6.0-SNAPSHOT
It will be released as part of IRS with the upcoming release

**Comment by mkanal** [comment]
Discussed in the Daily - Done Tests are green.
